variables:
  CI: true

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  # Install dependencies
  - script: npm install
    displayName: 'Install dependencies'
  
  - script: npm install --only=dev redux-immutable-state-invariant enzyme@3.8.0 enzyme-adapter-react-16@1.7.1 chai expect jsdom mocha react-addons-test-utils sinon
    displayName: 'Install dev dependencies'
  
  - script: npm run test:ci
    displayName: 'Run unit tests'
      
  - script: export REACT_APP_BUILD_NUMBER=$(Build.BuildNumber) && npm run build
    displayName: 'Build react app'

  # Publish unit tests
  - task: PublishTestResults@2
    continueOnError: true
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test/junit.xml' 
      searchFolder: '$(System.DefaultWorkingDirectory)'
      mergeTestResults: true
      #testRunTitle: # Optional
      #buildPlatform: # Optional
      #buildConfiguration: # Optional
      #publishRunAttachments: true # Optional

  # Zip build output
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/promotions-manager-ui.$(Build.BuildId).tar.gz'
      includeRootFolder: false

  # Publish Build Artifact
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'drop'
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/'      

# Publish build artifact to colony artifacts repo
# - job: UploadArtifactToColonyRepo
#   pool:
#     vmImage: 'vs2017-win2016'

#   steps:
#   - checkout: none  #skip checking out the default repository resource
#   - task: DownloadPipelineArtifact@0
#     displayName: 'Download Pipeline Artifacts'
#     inputs:
#       artifactName: 'drop'
#       downloadPath: $(System.DefaultWorkingDirectory)

#   - task: MFelling.AzureStorageUpload.custom-build-task.AzureStorageUpload@0
#     displayName: 'Upload file Azure Storage'
#     inputs:
#       Source: '$(System.DefaultWorkingDirectory)'
#       Pattern: 'promotions-manager-ui.$(Build.BuildId).zip'
#       Dest: 'https://colonynjzkmtjjzdfl30067.file.core.windows.net/artifacts/'
#       DestKey: '$(AzureStorageSecretKey)'

#   dependsOn: Build
#   condition: succeeded()